version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: expense-tracker-db-dev
    environment:
      POSTGRES_DB: ${DB_NAME:-expense_tracker}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: expense-tracker-backend-dev
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${DB_NAME:-expense_tracker}
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DEVTOOLS_RESTART_ENABLED: "true"
    ports:
      - "${BACKEND_PORT:-8080}:8080"
    volumes:
      - ./backend/src:/app/src
      - maven_cache:/root/.m2
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: expense-tracker-frontend-dev
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:${BACKEND_PORT:-8080}/api
      WATCHPACK_POLLING: "true"
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/package.json:/app/package.json
      - ./frontend/package-lock.json:/app/package-lock.json
      - ./frontend/tsconfig.json:/app/tsconfig.json
      - ./frontend/next.config.js:/app/next.config.js
      - ./frontend/tailwind.config.ts:/app/tailwind.config.ts
      - ./frontend/postcss.config.js:/app/postcss.config.js
      - frontend_node_modules:/app/node_modules
    depends_on:
      - backend

volumes:
  postgres_data_dev:
  maven_cache:
  frontend_node_modules:
