# Example secrets file - DO NOT commit actual secrets
# Use External Secrets Operator or GCP Secret Manager in production
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: expense-tracker
type: Opaque
stringData:
  database: expense_tracker
  username: postgres
  password: CHANGE_ME_IN_PRODUCTION
